module.exports = [
  ['★ +1 boost for 3 hours to random buff/debuff', 350],
  ['★ +1 boost for 3 hours to buff/debuff of choice', 675],
  ['★ +1 boost for 12 hours to random buff/debuff', 1045],
  ['★ +1 boost for 12 hours to buff/debuff of choice', 1355],
  ['★★ +1 boost for 2 days to random buff/debuff', 1715],
  ['★★★ +1 boost for 2 days to buff/debuff of choice', 2015],
  ['★ Cooldown time for next Redistribution use reduced 10%', 2315],
  ['★ Cooldown time for next Redistribution use reduced 25%', 2465],
  ['★★ Cooldown time for next Redistribution use reduced 33%', 2540],
  ['★★★ Cooldown time for next Redistribution use reduced 50%', 2590],
  ['★★★ +5 points you can apply to your current ability set', 2660],
  ['★★★★ +10 points you can apply to your current ability set', 2700],
  ['★★★ +2 points added to your pool permanently', 2720],
  ['★★★★ +4 points added to your pool permanently', 2730],
  ['★★★★★ +8 points added to your pool permanently', 2735],
  ['★ Random debuff is neutralized for 2 hours', 3085],
  ['★ Debuff of choice is neutralized for 2 hours', 3410],
  ['★ Random debuff is neutralized for 12 hours', 3730],
  ['★ Debuff of choice is neutralized for 12 hours', 4040],
  ['★★ Random debuff is neutralized for 2 days', 4350],
  ['★★★ Debuff of choice is neutralized for 2 days', 4600],
  ['★★★★★ Last Chance buff can be used one more time after it revives you', 4601],
  ['★ Cooldown time for a random buff reduced by 2 days', 4951],
  ['★ Cooldown time for a buff of choice reduced by 2 days', 5226],
  ['★ Cooldown time for a random buff reduced by 4 days', 5556],
  ['★ Cooldown time for a buff of choice reduced by 4 days', 5821],
  ['★★ Cooldown time for a random buff reduced by 1 week', 6131],
  ['★★★ Cooldown time for a buff of choice reduced by 1 week', 6351],
  ['★ Cooldown time for a random debuff increased by 2 days', 6701],
  ['★ Cooldown time for a debuff of choice increased by 2 days', 6976],
  ['★ Cooldown time for a random debuff increased by 4 days', 7306],
  ['★ Cooldown time for a debuff of choice increased by 4 days', 7571],
  ['★★ Cooldown time for a random debuff increased by 1 week', 7881],
  ['★★★ Cooldown time for a debuff of choice increased by 1 week', 8101],
  ['★ Equivalent of $50 USD in cash or your bank account + 3 days of natural life span', 8476],
  ['★ Equivalent of $100 USD in cash or your bank account + 4 days of natural life span', 8826],
  ['★★ Equivalent of $1,000 USD in cash or your bank account + 5 days of natural life span', 9006],
  ['★★★ Equivalent of $2,500 USD in cash or your bank account + 6 days of natural life span', 9091],
  ['★★★★ Equivalent of $5,000 USD in cash or your bank account + 1 week of natural life span', 9151],
  ['★★★★★ Equivalent of $10,000 USD in cash or your bank account + 2 weeks of natural life span', 9161],
  ['★ -1 day of natural life span applied to the person of your choice (excluding self)', 9361],
  ['★ -2 days of natural life span applied to the person of your choice  (excluding self)', 9522],
  ['★★ -3 days of natural life span applied to the person of your choice  (excluding self)', 9603],
  ['★★★★ -1 week of natural life span applied to the person of your choice  (excluding self)', 9634],
  ['★★ +1 day of natural life span applied to an animal of your choice (including self)', 9754],
  ['★★★ +3 days of natural life span applied to the person of your choice (including self)', 9835],
  ['★★★★ +1 week of natural life span applied to an animal of your choice (including self)', 9880],
  ['★★★★★ +2 weeks of natural life span applied to an animal of your choice (including self)', 9905],
  ['★★★★★ +1 month of natural life span applied to an animal of your choice (including self)', 9910],
  ['★★★★ Apply a debuff to a random person of your choice', 10000]
];
